services:
  db:
    image: mariadb:11
    container_name: db
    volumes:
      - wp_db:/var/lib/mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

  wordpress:
    image: wordpress:php8.2-apache
    container_name: wordpress
    depends_on:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
      # WORDPRESS_HOME: https://giankarlo.me/blog
      # WORDPRESS_SITEURL: https://giankarlo.me/blog
    volumes:
      - wp_data:/var/www/html/
  
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certbot-www:/var/www/certbot
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certs:/etc/letsencrypt
      - ./nginx/certbot-www:/var/www/certbot
    command:       
      certonly --webroot 
      --webroot-path=/var/www/certbot 
      --email ${USER_EMAIL} 
      --agree-tos 
      --no-eff-email 
      -d giankarlo.me 
      -d www.giankarlo.me

volumes:
  wp_db:
  wp_data: