version: '3.8'

services:
  db:
    image: mariadb:11
    volumes:
      - wp_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.2-apache
    ports:
      - "127.0.0.1:8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_HOME: https://giankarlo.me/blog
      WORDPRESS_SITEURL: https://giankarlo.me/blog
    volumes:
      - wp_data:/var/www/html

volumes:
  wp_db:
  wp_data: